### ISSUE TITLE
Adopt Convention Of Common `require` Entities Being Relative To Package Root

### ISSUE THREAD

**Issue by dyoder** [patchboard/patchboard#4]
For things like 

```
require "patchboard/client"
```

A client.js file can be placed in the package root, rather than forcing the more awkward

```
require "patchboard/lib/client"
```

Which, in turn, would fix (I think) the need to use --alias etc. when browserifying.

**Comment by dyoder** [comment]
Part of why I'm interested in this is that I'm trying to create rake tasks to streamline the process of using NPMs in Web apps. The task for Nice (for example) looks like

```
desc "Package Nice for use in browser"
task "build:nice" do
  browserify("nice")
  uglify("nice")
end
```

**Comment by automatthew** [comment]
Obviated by the separation of server and client packages.
