### ISSUE TITLE
Support Synchronous Requests From Client

### ISSUE THREAD

**Issue by dyoder** [patchboard/patchboard#7]
There are some cases where this might be necessary. For example, implementing a remote require. :)

**Comment by automatthew** [comment]
I'm still a little leery of the idea that JS requires should be a part of a REST API.

**Comment by dyoder** [comment]
It's just an example. The point is that the framework shouldn't enforce a
particular style. Or, if it does, we should have a good reason why. One
such reason is simplicity. A single interface is less work all around (less
documentation, fewer tests, less code to begin with, etc.). But it's
important to realize we are potentially eliminating some types of
applications. The `require` implementation is just one such scenario. Keep
in mind the way that asynchronous code tends to propagate back to the
caller.

**Comment by automatthew** [comment]
Presuming this were implemented in Shred, I suppose the method call would be identical, save for the "on" property?

**Comment by dyoder** [comment]
Here's what's funny. We could use node-fibers server side to make the call
synchronous. :)

**Comment by automatthew** [comment]
or icedcoffee, perhaps?
