### ISSUE TITLE
Handle WebP Application Headers From Mobile Vendors

### ISSUE THREAD

**Issue by freeformflow** [patchboard/patchboard#74]
@automatthew, 

I've got an interesting problem for you.  The engineers working with Flambe are having trouble with the application headers their web client is sending to the API server.  The application starts out with a header that looks like this:

```
application/vnd.playground.videos+json; version=1.0; charset=UTF-8
```

However, the mobile version of Chrome appends the request, so what the API server sees is: 

```
application/vnd.playground.videos+json; version=1.0; charset=UTF-8,image/webp
```

WebP is Google's new open source format, a competitor to JPEG, PNG, and GIF formats.  It apparently offers a superior compression algorithm and a smaller file size.  So it makes sense that this would exist on the mobile platforms.

Assuming that we cannot get rid what's appended to the header, is there a way to alter our setup to optionally accept the WebP sub-header?  Or would this require a change to Patchboard? 

cc @maheshyellai, @ArkenKiran, @skvedula

**Comment by automatthew** [comment]
This would be the Accept header?

**Comment by maheshyellai** [comment]
Yes @automatthew this would be in the Accept header.

**Comment by automatthew** [comment]
Accept headers aren't supposed to be exact match, so Patchboard is not doing the right thing.  We've known this for some time, but haven't had a use case that required fixing it yet.

I'll assess how much work is involved.

**Comment by automatthew** [comment]
Note the [TODO](https://github.com/patchboard/patchboard/blob/dispatchiness/src/matchers.coffee#L129).

**Comment by automatthew** [comment]
Related to #9

**Comment by automatthew** [comment]
Probable fix on branch `0.4.x`:

https://github.com/patchboard/patchboard/tree/0.4.x

**Comment by freeformflow** [comment]
@automatthew, thank you for your fast action.  I will speak to the team again on Sunday to talk about testing before I close this.  But, it sounds like you've solved this.

**Comment by freeformflow** [comment]
I just the update from Surya.  I'm closing this now.  Thank you again, Matthew.

**Comment by automatthew** [comment]
Happy to help.
